const brand = [
  {
    id: 1,
    brand: "Narciso",
  },
  {
    id: 2,
    brand: "Versace",
  },
  {
    id: 3,
    brand: "Hugo Boss",
  },
  {
    id: 4,
    brand: "Roja",
  },
  {
    id: 5,
    brand: "Gucci",
  },
  {
    id: 6,
    brand: "Chanel",
  },
  {
    id: 7,
    brand: "Dior",
  },
  {
    id: 8,
    brand: "Dolce",
  },
  {
    id: 9,
    brand: "Jean Paul Gaultier",
  },
];
const perfumeProducts = [
  {
    id: 1,
    brand: "Gucci",
    name: "Gucci Flora Love Edition ",
    gender: "Nam",
    img: "Nam/gucci/sp1.webp",
    imgDetail: "Nam/gucci/detail1.jpg",
    type: "100ml",
    description:
      "Hương hoa của Saeed Ghani Gucci Flora Attar hoàn hảo cho những phụ nữ yêu thích mùi ngọt ngào và đất. Hương thơm mở ra với hương đầu của trái cây và hoa trắng bao gồm cánh hoa lan Nam Phi, hoa nhài và hoa huệ. Ở lớp hương giữa là nét nữ tính và thanh lịch của hoa hồng và cây sơn chi mang hương thơm trung tâm. Di chuyển về phía nốt hương cuối, có những nốt hương gỗ và xạ hương mạnh mẽ làm cho mùi hương trở nên mạnh mẽ cũng như thanh lịch.",
    price: 3000000,
    origin: "Ý",
    rating: 5,
    isDealFragrant: true,
    isMini: true,
    isNew: false,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 2,
    brand: "Gucci",
    name: "Gucci Guilty Love Edition MMXXI EDT Men ",
    gender: "Nam",
    img: "Nam/gucci/sp2.jpg",
    imgDetail: "Nam/gucci/detail2.jfif",
    origin: "Ý",
    type: "100ml",
    description:
      "Gucci Guilty Pour Homme được Jacques Huclie sáng tạo ra mùi hương này dành cho những người biết được và giành lấy những gì họ muốn. Với hương thơm quyến rũ và khiêu khích, họ như thỏi nam châm thu hút mọi ánh nhìn và làm say đắm các quý cô.",
    price: 1000000,
    rating: 4.5,
    origin: "Ý",
    isDealFragrant: true,
    isNew: true,
    isMini: false,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 3,
    brand: "Gucci",
    name: "Nước Hoa Nam Gucci Guilty Black Pour Homme Men ",
    gender: "Nam",
    img: "Nam/gucci/sp3.jfif",
    imgDetail: "Nam/gucci/detail3.webp",
    type: "100ml",
    description:
      "Phiên bản mới của dòng nước hoa Gucci Guilty được cải tiến nhằm mang đến một phong cách mãnh liệt dựa trên hương thơm nam tính của Gucci Guilty Pour Homme. Tôn vinh sự tự do mà thương hiệu theo đuổi thông qua câu chuyện #ForeverGuilty, Gucci Guilty Pour Homme EDP tái hiện mùi hương ban đầu với sự kết hợp của ớt cay và hoa hồng tươi nhẹ nhàng. ",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: true,
    isNew: false,
    origin: "Ý",
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 4,
    brand: "Gucci",
    name: "Gucci Guilty Love Edition MMXXI EDT Men ",
    gender: "Nam",
    img: "Nam/gucci/sp4.jpeg",
    imgDetail: "Nam/gucci/detail4.png",
    origin: "Ý",
    type: "100ml",
    description:
      "Phiên bản dành cho nam với tên gọi Gucci by Gucci Pour Homme được sáng tạo bởi giám đốc sáng tạo của hãng Gucci là Frida Giannini, với sự hợp tác của Givaudan và P&G vào năm 2008. Hương nước hoa được biết đến như một hương gỗ Chypre hiện đại và bao gồm những hương như hoa tím và cây bách ở lớp đầu, lớp giữa gồm có hương của thuốc lá và hoa nhài, lớp nền bao gồm sự hiện diện của hoắc hương, hổ phách và dấu trám.",
    price: 1000000,
    isDealFragrant: false,
    rating: 4.5,
    isNew: true,
    isMini: false,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 5,
    brand: "Gucci",
    name: "Gucci Guilty Love Edition MMXXI EDT Men ",
    origin: "Ý",
    gender: "Nam",
    img: "Nam/gucci/sp5.jpg",
    imgDetail: "Nam/gucci/detail5.webp",
    type: "100ml",
    description:
      "Phiên bản dành cho nam với tên gọi Gucci by Gucci Pour Homme được sáng tạo bởi giám đốc sáng tạo của hãng Gucci là Frida Giannini, với sự hợp tác của Givaudan và P&G vào năm 2008. Hương nước hoa được biết đến như một hương gỗ Chypre hiện đại và bao gồm những hương như hoa tím và cây bách ở lớp đầu, lớp giữa gồm có hương của thuốc lá và hoa nhài, lớp nền bao gồm sự hiện diện của hoắc hương, hổ phách và dấu trám.",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: true,
    isNew: false,
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 6,
    brand: "Gucci",
    name: "Gucci Guilty Love Edition MMXXI EDT Men ",
    gender: "Nam",
    origin: "Ý",
    img: "Nam/gucci/sp6.jpg",
    imgDetail: "Nam/gucci/detail6.jpg",
    type: "100ml",
    description:
      "Phiên bản dành cho nam với tên gọi Gucci by Gucci Pour Homme được sáng tạo bởi giám đốc sáng tạo của hãng Gucci là Frida Giannini, với sự hợp tác của Givaudan và P&G vào năm 2008. Hương nước hoa được biết đến như một hương gỗ Chypre hiện đại và bao gồm những hương như hoa tím và cây bách ở lớp đầu, lớp giữa gồm có hương của thuốc lá và hoa nhài, lớp nền bao gồm sự hiện diện của hoắc hương, hổ phách và dấu trám.",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isDealFragrant: false,
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 7,
    brand: "Gucci",
    name: "Gucci Guilty Love Edition MMXXI EDT Men ",
    origin: "Ý",
    gender: "Nam",
    img: "Nam/gucci/sp7.webp",
    imgDetail: "Nam/gucci/detail7.jpg",
    type: "100ml",
    description:
      "Phiên bản dành cho nam với tên gọi Gucci by Gucci Pour Homme được sáng tạo bởi giám đốc sáng tạo của hãng Gucci là Frida Giannini, với sự hợp tác của Givaudan và P&G vào năm 2008. Hương nước hoa được biết đến như một hương gỗ Chypre hiện đại và bao gồm những hương như hoa tím và cây bách ở lớp đầu, lớp giữa gồm có hương của thuốc lá và hoa nhài, lớp nền bao gồm sự hiện diện của hoắc hương, hổ phách và dấu trám.",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: true,
    isNew: true,
    isBestSeller: false,
    isMini: false,
    quantity: 100,
  },
  {
    id: 8,
    brand: "Gucci",
    name: "Gucci Guilty Love Edition MMXXI EDT Men ",
    origin: "Ý",
    gender: "Nam",
    img: "Nam/gucci/sp8.jpg",
    imgDetail: "Nam/gucci/detail8.webp",
    type: "100ml",
    description:
      "Phiên bản dành cho nam với tên gọi Gucci by Gucci Pour Homme được sáng tạo bởi giám đốc sáng tạo của hãng Gucci là Frida Giannini, với sự hợp tác của Givaudan và P&G vào năm 2008. Hương nước hoa được biết đến như một hương gỗ Chypre hiện đại và bao gồm những hương như hoa tím và cây bách ở lớp đầu, lớp giữa gồm có hương của thuốc lá và hoa nhài, lớp nền bao gồm sự hiện diện của hoắc hương, hổ phách và dấu trám.",
    price: 1000000,
    rating: 4.5,
    isNew: false,
    isDealFragrant: false,
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 9,
    brand: "Gucci",
    name: "Gucci Flora Gorgeous Jasmine",
    origin: "Ý",
    gender: "Nam",
    img: "Nam/gucci/sp9.webp",
    imgDetail: "Nam/gucci/detail9.webp",
    type: "100ml",
    description:
      "Đúng như tên gọi của mùi hương, Hoa nhài là chủ thể được tô vẽ xinh đẹp trong Flora Gorgeous Jasmine. Nhài tươi thắm, tinh khôi và gợi cảm, ngọt ngào như những gì ta có thể tưởng tượng về một tiểu thư chuẩn mực. Nhài của Flora Gorgeous Jasmine được tô vẽ đậm nét tới mức ta có thể tận hưởng hương thơm dễ chịu này từ đầu tới cuối của mùi hương, nhưng vẫn đủ giúp ta nhận biết được sắc thái đem tới từ các vệ tinh xung quanh bông hoa dễ thương này, bằng việc chuyển biến của mùi hương.",
    price: 1000000,
    rating: 4.5,
    isNew: false,
    isMini: false,
    isDealFragrant: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 10,
    brand: "Gucci",
    name: "Gucci Bloom Ambrosia di Fiori Eau de Parfum ",
    gender: "Nam",
    origin: "Ý",
    img: "Nam/gucci/sp10.webp",
    imgDetail: "Nam/gucci/detail10.webp",
    type: "100ml",
    description:
      "Gucci Bloom au de Parfum là một người em của Gucci Bloom, tập trung khai thác nét đẹp của Hoa huệ dưới một góc nhìn nữ tính đầy thú vị.,Ambrosia di Fiori E",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: false,
    isNew: true,
    isBestSeller: false,
    isMini: true,
    quantity: 100,
  },
  {
    id: 11,
    name: "Jean Paul Gaultier Scandal  ",
    brand: "Jean Paul Gaultier",
    origin: "Pháp",
    gender: "Nam",
    img: "Nam/jeanpaul/sp1.jpg",
    imgDetail: "Nam/jeanpaul/detail1.webp",
    type: "100ml",
    description:
      "Người ta có câu, Hoa hồng dành cho đàn bà, Phong lữ dành cho đàn ông.Thứ duy nhất mà hai nốt hương này cùng chia sẻ là làn hương lãng đãng, miên man, hơi sắc nhưng không thiếu đi nét quyến rũ cần thiết. Mà hay thay Scandal Pour Homme Le Parfum lại lựa chọn Phong lữ để mở đầu. Sau đó mới dồn dập tấn công khứu giác của ta với vị ngọt thường trực của nhà Jean Paul Gaultier.",
    price: 3000000,
    rating: 5,
    isDealFragrant: true,
    isNew: true,
    isMini: false,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 12,
    name: "Jean Paul Gaultier Le ",
    brand: "Jean Paul Gaultier",
    origin: "Pháp",
    gender: "Nam",
    img: "Nam/jeanpaul/sp2.webp",
    imgDetail: "Nam/jeanpaul/detail2.webp",
    type: "100ml",
    description:
      "Ngay từ những giây đầu tiên, bạn những tưởng mình vẫn tìm thấy DNA đặc trưng của La Beau với mùi hương của Dứa, mọng ngọt và thanh chua. Nhưng tất cả diễn ra rất chóng vánh, nhanh đến nỗi khứu giác của bạn còn không nhận ra hương Gỗ thâm trầm, cùng Cây bách hăng hắc đã chiếm lĩnh bầu không khí tự bao giờ",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: false,
    isNew: false,
    isBestSeller: false,
    isMini: true,
    quantity: 100,
  },
  {
    id: 13,
    brand: "Jean Paul Gaultier",
    name: "Jean Paul Gaultier Scandal  ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/jeanpaul/sp3.webp",
    imgDetail: "Nam/jeanpaul/detail3.webp",
    type: "100ml",
    description:
      "Một người phụ nữ sau giai đoạn nổi loạn của tuổi trẻ sẽ còn lại gì? Cô hẳn không còn cái ngông cuồng như lúc trẻ, cũng không còn sự táo bạo điên loạn ấy. Thế nhưng thời gian đã đổi lại cho cô sự sắc sảo, sự khôn ngoan và tinh ranh cần thiết.",
    price: 1000000,
    rating: 4.5,
    isNew: false,
    isDealFragrant: true,
    isBestSeller: false,
    isMini: false,
    quantity: 100,
  },
  {
    id: 14,
    brand: "Jean Paul Gaultier",
    name: "Jean Paul Gaultier Scandal ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/jeanpaul/sp4.jpg",
    imgDetail: "Nam/jeanpaul/detail4.jpg",
    type: "100ml",
    description:
      "Năng lượng mạnh mẽ của chai nước hoa Jean Paul Gaultier Scandal Pour Homme được toát ra ngay từ giây phút đầu tiên của cam mát lạnh và xô thơm cuốn hút như một cú đấm dũng mãnh gây choáng cho đối phương. Lớp hương trái tim là hỗn hợp độc đáo đến từ đậu tonka béo ngậy cùng lớp caramel nồng nàn làm gia tăng độ quyến rũ. Mùi hương không thể cưỡng lại này kết hợp giữa ý chí cùng khát khao chiến thắng, nó giúp đánh thức các giác quan, tiếp thêm nguồn sức mạnh để đạt được ước mơ. Khi các lớp hương trước dần phai đi, note hương nhẹ nhàng của cỏ hương bài đọng lại vô cùng tinh tế, giúp cho mùi hương trở nên ấn tượng hơn.",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: false,
    isNew: true,
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 15,
    brand: "Jean Paul Gaultier",
    name: " Jean Paul  Le Parfum EDP Intense ",
    origin: "Pháp",
    gender: "Nam",
    img: "Nam/jeanpaul/sp5.png",
    imgDetail: "Nam/jeanpaul/detail5.jpeg",
    type: "100ml",
    description:
      "Lại một siêu phẩm mùi hương nữa vừa được Jean Paul Gaultier cho ra mắt trong năm 2022 – Nước hoa Jean Paul Gaultier Scandal Le Parfum. Vẫn là thiết kế đặc trưng với đôi chân dài thu hút, tuy nhiên với phiên bản lần này, Jean Paul Gaultier sử dụng sắc đỏ đại diện cho hổ phách càng làm Scandal Le Parfum Intense trở nên khiêu khích, bắt mắt hơn rất nhiều lần.Phiên bản dành cho nam với tên gọi Gucci by Gucci Pour Homme được sáng tạo bởi giám đốc sáng tạo của hãng Gucci là Frida Giannini, với sự hợp tác của Givaudan và P&G vào năm 2008. Hương nước hoa được biết đến như một hương gỗ Chypre hiện đại và bao gồm những hương như hoa tím và cây bách ở lớp đầu, lớp giữa gồm có hương của thuốc lá và hoa nhài, lớp nền bao gồm sự hiện diện của hoắc hương, hổ phách và dấu trám.",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: true,
    isNew: true,
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 16,
    brand: "Jean Paul Gaultier",
    name: "Gucci Guilty Love Edition  ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/jeanpaul/sp6.png",
    imgDetail: "Nam/jeanpaul/detail6.jpeg",
    type: "100ml",
    description:
      "Phiên bản dành cho nam với tên gọi Gucci by Gucci Pour Homme được sáng tạo bởi giám đốc sáng tạo của hãng Gucci là Frida Giannini, với sự hợp tác của Givaudan và P&G vào năm 2008. Hương nước hoa được biết đến như một hương gỗ Chypre hiện đại và bao gồm những hương như hoa tím và cây bách ở lớp đầu, lớp giữa gồm có hương của thuốc lá và hoa nhài, lớp nền bao gồm sự hiện diện của hoắc hương, hổ phách và dấu trám.",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: false,
    isNew: false,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 17,
    brand: "Jean Paul Gaultier",
    name: "Jean Paul Gaultier Le Male EDT ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/jeanpaul/sp7.jpg",
    imgDetail: "Nam/jeanpaul/detail7.jpg",
    type: "100ml",
    description:
      "Jean Paul Gaultier đã sử dụng hình ảnh người phụ nữ mặc áo nịt làm biểu tượng chính trong thiết kế dòng nước hoa cho nữ. Và ông ấy chuyển đổi một người đàn ông trong hình tượng thủy thủ mặc áo sơ mi để làm biểu tượng và thiết kế chai của Le Male.",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: true,
    isNew: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 18,
    brand: "Jean Paul Gaultier",
    name: "Gucci Guilty Love  Men ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/jeanpaul/sp8.jpg",
    imgDetail: "Nam/jeanpaul/detail8.jpg",
    type: "100ml",
    description:
      "Phiên bản dành cho nam với tên gọi Gucci by Gucci Pour Homme được sáng tạo bởi giám đốc sáng tạo của hãng Gucci là Frida Giannini, với sự hợp tác của Givaudan và P&G vào năm 2008. Hương nước hoa được biết đến như một hương gỗ Chypre hiện đại và bao gồm những hương như hoa tím và cây bách ở lớp đầu, lớp giữa gồm có hương của thuốc lá và hoa nhài, lớp nền bao gồm sự hiện diện của hoắc hương, hổ phách và dấu trám.",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: false,
    isNew: false,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 19,
    brand: "Jean Paul Gaultier",
    name: "Jean Paul Gaultier Le Beau for men",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/jeanpaul/sp9.webp",
    imgDetail: "Nam/jeanpaul/detail9.webp",
    type: "100ml",
    description:
      "Với chỉ vỏn vẹn 3 nốt hương nhưng Le Beau vẫn khiến cho mọi anh chàng choáng ngợp với đẳng cấp của mùi hương này. Le Beau bắt đầu với vị tươi mát của Cam bergamot, một chút thanh chua và nhẹ nhàng đem lại cảm giác an toàn và dễ chịu cho người dùng. Trong vị chua ấy vẫn len lỏi vị ngọt của Dừa, ngôi sao chính của Le Beau. Sang đến tầng hương sau, hương Dừa cùng với đậu Tonka thật sự tỏa sáng với vị ngọt ngào pha lẫn bùi béo. Đến đây bạn sẽ được gặp lại anh chàng nhà Jean Paul Gaultier, một chàng bad boy bảnh trai mặc áo khoác da, ngồi trên chiếc xe phân khối lớn với tính cách phong trần, đầy phiêu lưu. ",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isDealFragrant: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 20,
    brand: "Jean Paul Gaultier",
    name: "Jean Paul Gaultier Le Beau for men",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/jeanpaul/sp10.webp",
    imgDetail: "Nam/jeanpaul/detail10.jpg",
    type: "100ml",
    description:
      " Bloom au de Parfum là một người em của Gucci Bloom, tập trung khai thác nét đẹp của Hoa huệ dưới một góc nhìn nữ tính đầy thú vị.,Ambrosia di Fiori E",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isMini: true,
    isDealFragrant: false,
    isBestSeller: false,
    quantity: 100,
  },
  // Narciso
  {
    id: 21,
    brand: "Narciso",
    name: "Narciso Rodriguez For Her Forever",
    description:
      "Hoa huệ và Nhài đóng vai trò chính khi tạo nên linh hồn cho Narciso Rodriguez for Her Forever, sau đó, khi mà đã yên vị trên làn da ta, mới bắt đầu dẫn dắt khứu giác đến những ngọt ngào lôi cuốn của Mộc tê và Dành dành. Xạ hương luôn là một yếu tố không thể thiếu khi nói về các ấn phẩm nhà Narciso, bởi chính cái bông phấn sạch sẽ ấy đã tạo nên cảm giác ngây thơ nhưng vô cùng quyến rũ kia. Dưới bàn tay chế tác của nhà hãng, tổ hợp Xạ hương và Hoa trắng dường như sống động và chân thực hơn bội phần. ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp1.webp",
    imgDetail: "Nam/narciso/detail1.webp",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: false,
    isDealFragrant: true,
    isBestSeller: true,
    quantity: 100,
  },
  {
    id: 22,
    brand: "Narciso",
    name: " Narciso Rodriguez  Noir EDP ",
    description:
      "Hoa huệ và Nhài đóng vai trò chính khi tạo nên linh hồn cho Narciso Rodriguez for Her Forever, sau đó, khi mà đã yên vị trên làn da ta, mới bắt đầu dẫn dắt khứu giác đến những ngọt ngào lôi cuốn của Mộc tê và Dành dành. Xạ hương luôn là một yếu tố không thể thiếu khi nói về các ấn phẩm nhà Narciso, bởi chính cái bông phấn sạch sẽ ấy đã tạo nên cảm giác ngây thơ nhưng vô cùng quyến rũ kia. Dưới bàn tay chế tác của nhà hãng, tổ hợp Xạ hương và Hoa trắng dường như sống động và chân thực hơn bội phần. ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp2.jpg",
    imgDetail: "Nam/narciso/detail2.jpg",
    type: "100ml",
    price: 1000000,
    isDealFragrant: false,
    rating: 4.5,
    isNew: false,
    isBestSeller: true,
    isMini: true,
    quantity: 100,
  },
  {
    id: 23,
    brand: "Narciso",
    name: "Narciso Rodriguez For Him Bleu Noir Parfum ",
    description:
      "Ta thường nghĩ Hoa và Phấn sẽ được đo đóng cho phái đẹp, nhưng thực tế luôn có những trường hợp đặc biệt. Diên vĩ là nốt đặc biệt mà chúng ta cần lưu tâm, một bông hoa tím, đầy ắp phấn trên những cánh hoa, nhưng mùi hương lại tôn lên vẻ nam tính thanh lịch, nhẵn nhụi. Dior Homme, Valentino Uomo hay Givenchy Gentleman đều là những dòng hương nổi tiếng đã khai thác hiệu quả nốt hương này dành cho các mùi hương nam giới. Và Narciso Rodriguez cũng không đứng ngoài cuộc, khi “chơi đùa” với nốt hương này một cách đậm chất Narciso trong mùi hương của Bleu Noir Parfum. ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp3.jpg",
    imgDetail: "Nam/narciso/detail3.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: false,
    isDealFragrant: true,
    isBestSeller: true,
    quantity: 100,
  },
  {
    id: 24,
    brand: "Narciso",
    name: "Narciso Rodriguez For Him Bleu Noir ",
    description:
      "Narciso Rodriguez For Him Bleu Noir Parfum được thiết kế với trọng tâm là mùi hương của Diên vĩ, cùng một nốt hương đặc trưng trứ danh của nhà mốt, ấy là Xạ hương. Xạ hương của Narciso Rodriguez luôn bông xốp, mềm mịn, càng tăng cường thêm hiệu ứng phấn mịn của bông hoa tím Diên vĩ. ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp4.jpg",
    imgDetail: "Nam/narciso/detail4.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isDealFragrant: true,
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 25,
    brand: "Narciso",
    name: "Narciso Rodriguez  Parfum Travel Spray ",
    description:
      "Nước hoa mang lại mùi hương cho cơ thể bạn thông qua việc tiếp xúc lên da và phản ứng với hơi ấm trên cơ thể của bạn. Việc được tiếp xúc với các bộ phận như cổ tay, khuỷu tay, sau tai, gáy, cổ trước là những vị trí được ưu tiên hàng đầu trong việc sử dụng nước hoa bởi sự kín đáo và thuận lợi trong việc tỏa mùi hương. ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp5.webp",
    imgDetail: "Nam/narciso/detail5.webp",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: false,
    isDealFragrant: false,
    isBestSeller: true,
    quantity: 100,
  },
  {
    id: 26,
    brand: "Narciso",
    name: "Narciso Rodriguez Noir Parfum Travel  ",
    description:
      "Nước hoa có thể bám tốt hay không tốt tùy thuộc vào thời gian, không gian, cơ địa, chế độ sinh hoạt, ăn uống của bạn, việc sử dụng một loại nước hoa trong thời gian dài có thể khiến bạn bị quen mùi, dẫn đến hiện tượng không nhận biết được mùi hương. Mang theo nước hoa bên mình hoặc trang bị những mẫu mini tiện dụng để giúp bản thân luôn tự tin mọi lúc mọi nơi.",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp6.webp",
    imgDetail: "Nam/narciso/detail6.webp",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: true,
    isNew: true,
    isBestSeller: true,
    isMini: true,
    quantity: 100,
  },
  {
    id: 27,
    brand: "Narciso",
    name: "Narciso Rodriguez Noir Parfum Travel  ",
    description:
      "Nước hoa có thể bám tốt hay không tốt tùy thuộc vào thời gian, không gian, cơ địa, chế độ sinh hoạt, ăn uống của bạn, việc sử dụng một loại nước hoa trong thời gian dài có thể khiến bạn bị quen mùi, dẫn đến hiện tượng không nhận biết được mùi hương. Mang theo nước hoa bên mình hoặc trang bị những mẫu mini tiện dụng để giúp bản thân luôn tự tin mọi lúc mọi nơi.",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp7.webp",
    imgDetail: "Nam/narciso/detail7.jfif",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: false,
    isDealFragrant: false,
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 28,
    brand: "Narciso",
    name: "Narciso Rodriguez Noir Parfum Travel  ",
    description:
      "Nước hoa có thể bám tốt hay không tốt tùy thuộc vào thời gian, không gian, cơ địa, chế độ sinh hoạt, ăn uống của bạn, việc sử dụng một loại nước hoa trong thời gian dài có thể khiến bạn bị quen mùi, dẫn đến hiện tượng không nhận biết được mùi hương. Mang theo nước hoa bên mình hoặc trang bị những mẫu mini tiện dụng để giúp bản thân luôn tự tin mọi lúc mọi nơi.",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp8.webp",
    imgDetail: "Nam/narciso/detail8.jfif",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isDealFragrant: true,
    isBestSeller: true,
    quantity: 100,
  },
  {
    id: 29,
    brand: "Narciso",
    name: "Narciso Rodriguez Noir Parfum Travel  ",
    description:
      "Nước hoa có thể bám tốt hay không tốt tùy thuộc vào thời gian, không gian, cơ địa, chế độ sinh hoạt, ăn uống của bạn, việc sử dụng một loại nước hoa trong thời gian dài có thể khiến bạn bị quen mùi, dẫn đến hiện tượng không nhận biết được mùi hương. Mang theo nước hoa bên mình hoặc trang bị những mẫu mini tiện dụng để giúp bản thân luôn tự tin mọi lúc mọi nơi.",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp9.jfif",
    imgDetail: "Nam/narciso/detail9.jfif",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isMini: true,
    isNew: false,
    isDealFragrant: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 30,
    brand: "Narciso",
    name: "Narciso Rodriguez Noir Parfum Travel  ",
    description:
      "Nước hoa có thể bám tốt hay không tốt tùy thuộc vào thời gian, không gian, cơ địa, chế độ sinh hoạt, ăn uống của bạn, việc sử dụng một loại nước hoa trong thời gian dài có thể khiến bạn bị quen mùi, dẫn đến hiện tượng không nhận biết được mùi hương. Mang theo nước hoa bên mình hoặc trang bị những mẫu mini tiện dụng để giúp bản thân luôn tự tin mọi lúc mọi nơi.",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp10.webp",
    imgDetail: "Nam/narciso/detail10.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isDealFragrant: false,
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  // versace
  {
    id: 31,
    brand: "Versace",
    name: "Versace Pour Homme Oud Noir  ",
    description:
      "Không quá lời khi nói rằng, Versace Eros là mùi hương lấy lại vị thế cho nhà mốt lừng danh đến từ đất nước nước hình chiếc ủng trong thế kỷ 21. Tươi trẻ, sôi động và gợi cảm, đó là những tính từ có thể dùng để mô tả sát nghĩa nhất mùi hương nằm trong chai hương màu xanh đậm dấu ấn Địa Trung Hải này",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/narciso/sp6.webp",
    isMini: true,
    imgDetail: "Nam/narciso/detail6.webp",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: true,
    isNew: false,
    isMini: true,
    isBestSeller: true,
    quantity: 100,
  },
  {
    id: 32,
    brand: "Versace",
    name: "Versace Eros Flame EDP ",
    description:
      "Versace Eros Flame được ra mắt vào năm 2018, được miêu tả như một dòng cảm xúc chứa đầy nội tâm cùng những sắc thái biểu cảm xung đột, mâu thuẫn đầy tâm trạng của những người đàn ông với vẻ bề ngoài mạnh mẽ, tự tin và thành đạt. Vẫn giữ lại sự cuốn hút và nam tính của người anh Eros, nhưng sự phá cách trong cách tạo mùi hương của hãng Versace đã tạo ra một Eros Flame đầy cá tính với các tone mùi mang hương vị cam quýt và gỗ đàn hương, vani và tiêu đen",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/versace/sp2.webp",
    imgDetail: "Nam/versace/detail2.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: false,
    isNew: true,
    isMini: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 33,
    brand: "Versace",
    name: "Versace Eros Flame EDP ",
    description:
      "Versace Eros Flame được ra mắt vào năm 2018, được miêu tả như một dòng cảm xúc chứa đầy nội tâm cùng những sắc thái biểu cảm xung đột, mâu thuẫn đầy tâm trạng của những người đàn ông với vẻ bề ngoài mạnh mẽ, tự tin và thành đạt. Vẫn giữ lại sự cuốn hút và nam tính của người anh Eros, nhưng sự phá cách trong cách tạo mùi hương của hãng Versace đã tạo ra một Eros Flame đầy cá tính với các tone mùi mang hương vị cam quýt và gỗ đàn hương, vani và tiêu đen",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/versace/sp3.jpg",
    imgDetail: "Nam/versace/detail3.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isDealFragrant: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 34,
    brand: "Versace",
    name: "Versace Pour Homme Hair & Body Shampoo ",
    description:
      "Versace Eros Flame được raNước hoa mang lại mùi hương cho cơ thể bạn thông qua việc tiếp xúc lên da và phản ứng với hơi ấm trên cơ thể của bạn. Việc được tiếp xúc với các bộ phận như cổ tay, khuỷu tay, sau tai, gáy, cổ trước là những vị trí được ưu tiên hàng đầu trong việc sử dụng nước hoa bởi sự kín đáo và thuận lợi trong việc tỏa mùi hương.",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/versace/sp4.webp",
    imgDetail: "Nam/versace/detail4.webp",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isDealFragrant: true,
    isNew: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 35,
    brand: "Versace",
    name: "Combo Versace Pour Homme ",
    description:
      "Versace Eros Flame được ra mắt vào năm 2018, được miêu tả như một dòng cảm xúc chứa đầy nội tâm cùng những sắc thái biểu cảm xung đột, mâu thuẫn đầy tâm trạng của những người đàn ông với vẻ bề ngoài mạnh mẽ, tự tin và thành đạt. Vẫn giữ lại sự cuốn hút và nam tính của người anh Eros, nhưng sự phá cách trong cách tạo mùi hương của hãng Versace đã tạo ra một Eros Flame đầy cá tính với các tone mùi mang hương vị cam quýt và gỗ đàn hương, vani và tiêu đen",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/versace/sp5.jpg",
    imgDetail: "Nam/versace/detail5.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: false,
    isBestSeller: true,
    isMini: true,
    isDealFragrant: false,
    quantity: 100,
  },
  {
    id: 36,
    brand: "Versace",
    name: "Versace Eros Flame EDP ",
    description:
      "Versace Pour Homme mở đầu với hương thơm cam chanh sảng khoái, gây một chút liên tưởng tới sự mát mẻ của Acqua di Giò, nhưng tăng lên một chút hứng khởi trong thái độ của mùi hương. Xô thơm tươi, xanh, sáng màu, đẩy lên một sắc thái nam tính rõ ràng theo một cách cổ điển kiểu thảo mộc cho mùi hương Versace Pour Homme. Trẻ trung, năng động nhưng cũng đủ cứng cáp và rắn rỏi. Về hậu hương, chai nước hoa này đem tới cho các chàng trai một hương ngọt dịu bám lấy da dai dẳng hơn hẳn những gì chúng ta có với Acqua di Giò. ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/versace/sp6.jpg",
    imgDetail: "Nam/versace/detail6.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isBestSeller: false,
    isDealFragrant: true,
    quantity: 100,
  },
  {
    id: 37,
    brand: "Versace",
    name: "Nước Hoa Nam Versace Man Eau Fraiche EDT ",
    description:
      "Versace Eros Flame được ra mắt vào năm 2018, được miêu tả như một dòng cảm xúc chứa đầy nội tâm cùng những sắc thái biểu cảm xung đột, mâu thuẫn đầy tâm trạng của những người đàn ông với vẻ bề ngoài mạnh mẽ, tự tin và thành đạt. Vẫn giữ lại sự cuốn hút và nam tính của người anh Eros, nhưng sự phá cách trong cách tạo mùi hương của hãng Versace đã tạo ra một Eros Flame đầy cá tính với các tone mùi mang hương vị cam quýt và gỗ đàn hương, vani và tiêu đen",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/versace/sp7.jpg",
    imgDetail: "Nam/versace/detail7.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isDealFragrant: false,
    isBestSeller: true,
    quantity: 100,
  },
  {
    id: 38,
    brand: "Versace",
    name: "Versace Pour Homme Dylan Blue Mini Size ",
    description:
      "Versace Pour Homme Dylan Blue được ra mắt vào cuối tháng 7 năm 2016, là một chai nước hoa mới nhất của dòng Versace Pour Homme. Với nhiều người, hẳn sẽ để ý đến thiết kế chai rất sang trọng và tinh tế, nhưng với tôi, tôi chú đến màu xanh đậm của Versace Pour Homme Dylan Blue nhiều hơn. Nó tạo cả giác gần gũi đến lạ kỳ, màu xanh nước biển, màu xanh đậm của bầu trời, và tôi đã không hề sai, Dylan Blue chứa hương thơm của nước, xanh trong và tinh khiết. ",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/versace/sp8.webp",
    imgDetail: "Nam/versace/detail8.webp",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isMini: true,
    isDealFragrant: true,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 39,
    brand: "Versace",
    name: "Versace Eros Man EDT ",
    description:
      "Versace Eros Flame được ra mắt vào năm 2018, được miêu tả như một dòng cảm xúc chứa đầy nội tâm cùng những sắc thái biểu cảm xung đột, mâu thuẫn đầy tâm trạng của những người đàn ông với vẻ bề ngoài mạnh mẽ, tự tin và thành đạt. Vẫn giữ lại sự cuốn hút và nam tính của người anh Eros, nhưng sự phá cách trong cách tạo mùi hương của hãng Versace đã tạo ra một Eros Flame đầy cá tính với các tone mùi mang hương vị cam quýt và gỗ đàn hương, vani và tiêu đen",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/versace/sp9.jpg",
    imgDetail: "Nam/versace/detail9.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: false,
    isDealFragrant: false,
    isBestSeller: false,
    quantity: 100,
  },
  {
    id: 40,
    brand: "Versace",
    name: "Versace Pour Homme Dylan Blue EDT  ",
    description:
      "Versace Eros Flame được ra mắt vào năm 2018, được miêu tả như một dòng cảm xúc chứa đầy nội tâm cùng những sắc thái biểu cảm xung đột, mâu thuẫn đầy tâm trạng của những người đàn ông với vẻ bề ngoài mạnh mẽ, tự tin và thành đạt. Vẫn giữ lại sự cuốn hút và nam tính của người anh Eros, nhưng sự phá cách trong cách tạo mùi hương của hãng Versace đã tạo ra một Eros Flame đầy cá tính với các tone mùi mang hương vị cam quýt và gỗ đàn hương, vani và tiêu đen",
    gender: "Nam",
    origin: "Pháp",
    img: "Nam/versace/sp10.jpg",
    imgDetail: "Nam/versace/detail10.jpg",
    type: "100ml",
    price: 1000000,
    rating: 4.5,
    isNew: true,
    isDealFragrant: true,
    isBestSeller: true,
    quantity: 100,
  },
];
const coupon = [
  {
    id: 0,
    title: "summer2023",
    discount: 10,
  },
  {
    id: 1,
    title: "summer2024",
    discount: 20,
  },
  {
    id: 2,
    title: "summer2025",
    discount: 30,
  },
  {
    id: 3,
    title: "summer2026",
    discount: 40,
  },
  {
    id: 4,
    title: "summer2027",
    discount: 50,
  },
];

localStorage.setItem("Coupon", JSON.stringify(coupon));
localStorage.setItem("Brands", JSON.stringify(brand));
localStorage.setItem("PerfumeProducts", JSON.stringify(perfumeProducts));